tasks:
    path: /tareas
    controller: App\Controller\TaskController::index
    
task_detail:
    path: /tarea/{id}
    controller: App\Controller\TaskController::detail

task_creation:
    path: /crear-tarea
    controller: App\Controller\TaskController::creation
    
my_tasks:
    path: /mis-tareas
    controller: App\Controller\TaskController::myTasks
    
task_edit:
    path: /editar-tarea/{id}
    controller: App\Controller\TaskController::edit
    
task_delete:
    path: /borrar-tarea/{id}
    controller: App\Controller\TaskController::delete
    
register:
    path: /registro
    controller: App\Controller\UserController::register
    
login:
    path: /
    controller: App\Controller\UserController::login
modify:
    path: /modificar-perfil/{id}
    controller: App\Controller\UserController::Modify

contrase単a:
    path: /modificar-contrasena
    controller: App\Controller\Contrase単a::reset

usuarios:
    path: /usuarios
    controller: App\Controller\UserController::usuarios    
     
     
usuarios_delete:
    path: /usuarios-delete/{id}
    controller: App\Controller\UserController::usuarios_delete         
     
     
usuarios_ver:
    path: /ver-usuario/{id}
    controller: App\Controller\UserController::usuarios_ver     
    
usuarios_editar:
    path: /editar-usuario/{id}
    controller: App\Controller\UserController::usuarios_editar    

usuarios_editar_contrase単a:
    path: /editar-usuario-contrasena/{id}
    controller: App\Controller\UserController::usuarios_editar_contrase単a    

cuenta-cambiar:
    path: cambiar
    controller: App\Controller\ResetPasswordController::reset


cuenta-recordar:
    path: recordar
    controller: App\Controller\ResetPasswordController::request

contactar:
    path: /contactar/{id}
    controller: App\Controller\UserController::contactar    

asignar_tarea:
    path: /asignar-tarea/{id}
    controller: App\Controller\UserController::asignar_tarea    

logout:
    path: /logout

MailerController:
    path: /email
    controller: App\Controller\MailerController::sendEmail

